site_name: My Docs with Variables
extra_javascript:
  - js/variables.js
theme:
  name: material
  features:
    - navigation.footer

  
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
- Index: index.md
- Page1: page1.md
- PageInsideL: nai/page1.md